#Site
name:             Your New Jekyll Site
url:              http://localhost:4000

#House Keeping
markdown:         redcarpet
pygments:         true
regeneration:     -w 
exclude:          ['Gemfile', 'Gemfile.lock', '.ruby-version']

#Asset Pipline
assets:
  js_compressor:  uglifier
  css_compressor: sass