#Site
name:             Your New Jekyll Site
url:              http://localhost:4000

#House Keeping
markdown:         redcarpet
pygments:         true
regeneration:     -w 
exclude:          ['Gemfile', 'Gemfile.lock', '.gitignore', '.ruby-version', 'Rakefile', 'README.md', '.DS_Store']

#Asset Pipline
assets:
  js_compressor:  uglifier
  css_compressor: sass
  baseurl: assets/