#Site
name:             Ezextenz Concrete Chute
url:              http://ezextenz.com

#House Keeping
markdown:         redcarpet
pygments:         true
regeneration:     -w 
exclude:          ['Gemfile', 'Gemfile.lock', '.gitignore', '.ruby-version', 'Rakefile', 'README.md', '.DS_Store']

#Asset Pipline
assets:
  js_compressor:  uglifier
  css_compressor: sass
  baseurl: assets/
  
#Glynn
ftp_host: 'ftp.ezextenz.com'
ftp_dir: '/'
ftp_passive: false
ftp_username: 'ezextenz.com'